name: '🚀 Deploy Web Ui'

on:
  push:
    branches:
        - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        concurrency: ci-${{github.ref}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure Node
              uses: actions/setup-node@v4
              with:
                node-version: '22.x'
            - name: Install dependecies
              run: |
                npm ci
                npm run build -- "--base-href=\"/tm-task-manager-web-ui/\""

            - name: Debug Output
              run: grep 'base href' build/browser/index.html

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: build/browser

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4


